### ISSUE TITLE
Update Makefile: Add missing "standard" recipes

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-cert#471]
## Overview

Update this project's Makefile to add recipes from other projects that I maintain.

## TODO

- arch and OS-specific builds
  - [x] `windows-x86`
  - [x] `windows-x64`
  - [x] `windows` (a "wrapper" around the two arch-specific options)
  - [x] `linux-x86`
  - [x] `linux-x64`
  - [x] `linux` (a "wrapper" around the two arch-specific options)
- [x] `release-build`
  - used to generate just the binaries provided by a specific project (e.g., skip Windows (all), skip Linux x86)
- [x] `links` (and arch-specific variations)
  - used to generate download links for easier bulk retrieval of release assets
- [x] `quick`
  - `go build` without any custom settings applied
  - it is a *quick* build to test/prototype binaries without waiting for release-level optimizations to be applied
- [x] `depsinstall`
  - can replace `gogeninstall` as directly referenced by (at least a few) workflows
    - `atc0005/shared-project-resources/.github/workflows/lint-and-build-using-make.yml`
    - `atc0005/check-mail/.github/workflows/lint-and-build.yml`
  - `gogeninstall` can remain as a Makefile recipe for other projects, but would be called as part of the `depsinstall` recipe
  - `depsinstall` could become a dependency for other Makefile recipes and wouldn't need to be called directly by workflows
